export {default as Hero} from './Hero/Hero'
export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer'
export {default as Card} from './Card/Card'
export {default as About} from './About/About'